In [ ]:
""" FINAL GOAL IS:
    =============
    You get an address and your program models that house in 3D
"""

In [ ]:
"""
The request for this challenge:
==============================
- <what?> Given a random home address, model a house in 3D
- <why?> This can help the insurance business
"""

In [ ]:
"""
Steps:
=====
-1- download the maps 
-2- Identify the technical challenges needed
"""

In [ ]:
"""
Step 1
Download the maps:
=================
DSM
"""

In [ ]:
"""
Step 2
Technical challeges:
===================
"""

In [ ]:
"""
- Shapefile:
  ---------  
    is a geospatial vector data format for geographic information system (GIS) software.
    The shapefile format can spatially describe vector features: points, lines and polygons, representing
    f.e. water wells, rivers, and lakes.
    Each item usually has attributes that describe it, such as name or temperature.

    -- Shapefile shape format (.shp)
        The main file contains the geometry data

    -- Shapefile shape index format (.shx)
        The index file contains positional index of the feature geometry and the same 100-byte header as the .shp ..

    -- Shapefile attribute format (.dbf)
        This file stores the attributes for each shape (using dBase IV format)

<source: wikipedia>

    -- use PyShp for reading and writing ESRI Shapefiles in pure Python (pip install pyshp)
"""

In [ ]:
"""
- GeoTIFF:
  -------
    is a standard .tif or image file format that includes additinoal spacing (georeferencing) information
    embedded in the .tif file as tags (tig tags).
    These tags can include the following raster metadata:
    -1- Spatial Extent (what aria does this dataset cover)
    -2- Coordinate reference system (what spatial projection : coordinate reference system is used to store
        the data?  Will it line up with other data?)
    -3- Resolution (The data appears to be in raster format; i.o.w. composed of pixels)
    -4- nodata value
    -5- How many layers are in the .tif file
    
<source: www.earthdatascience.org/ .. /intro-to-the-geotiff-file-format/

    -- use PyPi (is a noGDAL tool for reading geotiff files)
        --- noGDAL = Geospatial Python without GDAL
                (GDAL = a translator library for raster and vector geospatial data formats ...)
        (pip install geotiff) (pip install rioxarray)
"""

In [ ]:
"""
De data worden aangeboden in GeoTIFF-formaat met volgende parameters:

PARAMETER     WAARDE                  OPMERKINGEN
------------------------------------------------------------------------------------
Pixelgrootte  1 m / 5 m               Afhankelijk van het type product
Datatype      floating point 32 bit
Compressie    deflate
NoData Value  -9999
piramides     ja                      standaard berekend voor een versnelde weergave
colormaps     nee                     er is geen standaard legende toegepast
CRS           EPSG 31370              Belgische Lambert 1972 projectie
2.2           TAW                     Tweede Algemene Waterpassing

"""

In [ ]:
"""
Naamgeving downloadpakket
De naamgeving van het downloadpakket per artikel is gelijk aan de code van het artikel:
    Pakketnaam = “<codeArtikel>.zip”
     voorbeeld: “DHMVIIDTMRAS1m_k07.zip”

Mappenstructuur downloadpakket
In het downloadpakket per artikel zitten volgende mappen:
(Try to understand the data)

<pakketnaam>.zip
    └<pakketnaam>
        ├───<documenten>
        └───<formaatmap>
            └───<data>
"""

In [ ]:
"""
- Lidar:
  -----
    is a method for detertmining ranges (variable distance) by targeting an object with a laser and measuring
    the time for the reflected light to return to the receiver.  Linar can also be used to make digital
    3-D representations 
    
    f.e.: Forestry
            Lidar systems have also been applied to improve forestry management.
            Measurements are used to take inventory in forest plots as well as calculate individual tree heights,
            crown width and crown diameter.
    
<source: wikipedia>

    (pip install lidar)
<source: pypi.org/project/lidar>
"""

In [ ]:
""" Before starting to code:
    =======================
    THE PLAN:
    --------
        -- download all data from DSM and DTM form the 3D_houses.md
"""

In [ ]:
"""
try: numpy

Rasterio: access to geospatial raster data (numeric format)

"""

In [ ]:
""" check the given address """
import geopandas as gpd

address = "Lange Van Sterbeeckstraat 8 2060 Antwerpen"
gpd.tools.geocode(address)


In [ ]:
# with PyShp

import shapefile
shape = shapefile.Reader("data/DHMVII_vdc_k01.shp")
#first feature of the shapefile
feature = shape.shapeRecords()[0]
first = feature.shape.__geo_interface__  
print(first) # (GeoJSON format)
{'type': 'LineString', 'coordinates': ((0.0, 0.0), (25.0, 10.0), (50.0, 50.0))}


In [ ]:
"""
# with Fiona

import fiona
shape = fiona.open("data/DHMVII_vdc_k01.shp")
print(shape.schema)
{'geometry': 'LineString', 'properties': OrderedDict([(u'FID', 'float:11')])}
#first feature of the shapefile
first = shape.next()
print(first) # (GeoJSON format)
{'geometry': {'type': 'LineString', 'coordinates': [(0.0, 0.0), (25.0, 10.0), (50.0, 50.0)]}, 'type': 'Feature', 'id': '0', 'properties': OrderedDict([(u'FID', 0.0)])}

# with ogr:

from osgeo import ogr
file = ogr.Open("data/DHMVII_vdc_k01.shp")
shape = file.GetLayer(0)
#first feature of the shapefile
feature = shape.GetFeature(0)
first = feature.ExportToJson()
print(first) # (GeoJSON format)
{"geometry": {"type": "LineString", "coordinates": [[0.0, 0.0], [25.0, 10.0], [50.0, 50.0]]}, "type": "Feature", "properties": {"FID": 0.0}, "id": 0}

"""

In [ ]:
import pandas as pd
from dbfread import DBF
db_in_dbf = DBF("data/DHMVII_vdc_k01.dbf")
db = pd.DataFrame(db_in_dbf)
db


In [14]:
""" Read the DSM files"""

import numpy as np
import rasterio
from rasterio.plot import show

dsm_src = 'data/DHMVIIDSMRAS1m_k01/GeoTIFF/DHMVIIDSMRAS1m_k01.tif'
dsm_img = rasterio.open(dsm_src)
#show(dsm_img)
dsm_array = dsm_img.read()
print(dsm_array)
dsm_array.shape


[[[-9.999e+03 -9.999e+03 -9.999e+03 ...  1.275e+01  1.279e+01  1.280e+01]
  [-9.999e+03 -9.999e+03 -9.999e+03 ...  1.280e+01  1.281e+01  1.284e+01]
  [-9.999e+03 -9.999e+03 -9.999e+03 ...  1.284e+01  1.283e+01  1.288e+01]
  ...
  [ 4.520e+00  4.550e+00  4.570e+00 ...  1.680e+01  1.693e+01  1.690e+01]
  [ 4.490e+00  4.570e+00  4.580e+00 ...  1.691e+01  1.691e+01  1.695e+01]
  [ 4.480e+00  4.550e+00  4.570e+00 ...  1.687e+01  1.688e+01  1.691e+01]]]


(1, 9000, 17000)

In [15]:
""" Read the DTM files"""

import numpy as np
import rasterio
from rasterio.plot import show

dtm_src = 'data/DHMVIIDTMRAS1m_k01/GeoTIFF/DHMVIIDTMRAS1m_k01.tif'
dtm_img = rasterio.open(dtm_src)
#show(dtm_img)
dtm_array = dtm_img.read()
print(dtm_array)
dtm_array.shape


[[[-9.999e+03 -9.999e+03 -9.999e+03 ...  1.275e+01  1.279e+01  1.280e+01]
  [-9.999e+03 -9.999e+03 -9.999e+03 ...  1.280e+01  1.281e+01  1.284e+01]
  [-9.999e+03 -9.999e+03 -9.999e+03 ...  1.284e+01  1.283e+01  1.288e+01]
  ...
  [ 4.520e+00  4.550e+00  4.570e+00 ...  1.680e+01  1.693e+01  1.690e+01]
  [ 4.490e+00  4.570e+00  4.580e+00 ...  1.691e+01  1.691e+01  1.693e+01]
  [ 4.480e+00  4.550e+00  4.570e+00 ...  1.686e+01  1.688e+01  1.690e+01]]]


(1, 9000, 17000)

In [20]:
""" Make the heights visible < DSM minus DTM > """

height_dsm_min_dtm = dsm_array - dtm_array
height_dsm_min_dtm
height_dsm_min_dtm.shape

(1, 9000, 17000)

In [27]:
""" Make an image """
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
import seaborn as sns

#numpy_data = np.array([[1, 2], [3, 4]])
#b=df.iloc[:,1:].values
height_dsm_min_dtm[['label']].to_numpy()


# Distribution Plot
#sns.distplot(df.Attack)
# Density Plot
#sns.kdeplot(df.Attack, df.Defense)

<ipython-input-27-ef5a60683f8e>:9: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  height_dsm_min_dtm[['label']].to_numpy()


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
# since there are 3 bands
# we store in 3 different variables
band1 = dataset.GetRasterBand(1) # Red channel
band2 = dataset.GetRasterBand(2) # Green channel
band3 = dataset.GetRasterBand(3) # Blue channel

In [ ]:
b1 = band1.ReadAsArray()
b2 = band2.ReadAsArray()
b3 = band3.ReadAsArray()

In [ ]:
""" Read DSM & DTM """
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import geopandas as gpd

bounds = gpd.read_file('')




numpy array

In [ ]:
dir()